Add Arm Controller
thedropbears/pychargedup pull request #17
Opened 2023-01-16 09:48 UTC by Pokesi

2023-01-19 05:06 UTC, auscompgeek requested changes

2023-01-19 05:06 UTC, auscompgeek commented on components/arm.py
> +    EXTEND_GEAR_RATIO = (1 / 7) * (math.pi * 0.05)  # converts to meters
What is `0.05`? Could it have a name?

2023-01-19 05:06 UTC, auscompgeek commented on ids.py
> +class PwmPorts:
nit:
```suggestion
class PwmChannels:
```

2023-01-19 05:06 UTC, auscompgeek commented on components/arm.py
> +        self.absolute_encoder = DutyCycleEncoder(PwmPorts.arm_abs_encoder)
Out of curiosity, is there a particular reason we're wiring this to the roboRIO rather than the motor controller?

2023-01-19 05:39 UTC, OliverW10 commented on components/arm.py
> +    EXTEND_GEAR_RATIO = (1 / 7) * (math.pi * 0.05)  # converts to meters
```suggestion
    SPOOL_DIAMETER = 0.05
    EXTEND_GEAR_RATIO = (1 / 7) * (math.pi * SPOOL_DIAMETER)  # converts to meters
```

2023-01-22 05:02 UTC, auscompgeek reviewed
I don't think there's anything obviously problematic here, but I do have a couple of comments.

2023-01-22 13:30 UTC, OliverW10 commented on components/arm.py
> +        self._rotation_motor_right.follow(self.rotation_motor, True)
[to invert](https://robotpy.readthedocs.io/projects/rev/en/stable/rev/CANSparkMax.html#rev.CANSparkMax.follow)

2023-01-22 13:30 UTC, OliverW10 commented on components/arm.py
> +    EXTEND_GEAR_RATIO = (1 / 7) * (math.pi * SPOOL_DIAMETER)  # converts to meters
Changed to 'spool output ratio'

2023-01-23 03:59 UTC, auscompgeek approved these changes

2023-01-23 03:59 UTC, auscompgeek commented on components/arm.py
> +        self.rotation_simple_ff = SimpleMotorFeedforwardMeters(0.1, 0.5, 1)
Just curious: why not ArmFeedforward?

2023-01-24 08:29 UTC, merged