added solenoid control
thedropbears/pychargedup pull request #4
Opened 2023-01-10 09:51 UTC by fotnitfpro000

2023-01-28 05:52 UTC, LucienMorey requested changes

2023-01-28 05:52 UTC, LucienMorey commented on tests/vision.py
> +while True:
This file should not be in this commit

2023-01-28 05:52 UTC, LucienMorey commented on tests/vision1.py
> +while True:
This file should not be in this commit

2023-01-28 05:52 UTC, LucienMorey commented on robot.py
>          self.logger.info("pyrapidreact %s", GIT_INFO)
You will need to create an instance of the claw solenoid and make reference to the ids for it

2023-01-28 05:52 UTC, LucienMorey commented on components/claw.py
> +            self.gripper_solenoid.set(value=wpilib.DoubleSolenoid.Value.kReverse)
```suggestion
    def execute(self):
        if self.is_gripper_open:
            self.gripper_solenoid.set(value=wpilib.DoubleSolenoid.Value.kForward)
        else:
            self.gripper_solenoid.set(value=wpilib.DoubleSolenoid.Value.kReverse)
```

2023-01-28 05:52 UTC, LucienMorey commented on components/claw.py
> +        self.is_gripper_open = True
```suggestion
    self.gripper_solenoid: wpilib.DoubleSolenoid
    def __init__(self):
        self.is_gripper_open = True
```

2023-01-28 05:52 UTC, LucienMorey commented on components/claw.py
> +import wpilib
You could also consider importing just the things you need. ie ```DoubleSolenoid```

2023-01-29 03:34 UTC, DensityInfinite approved these changes

2023-01-29 03:36 UTC, DensityInfinite commented on components/gripper.py
> +    gripper_game_piece_switch: wpilib.DigitalInput
Should those be the ones from robot.py?

2023-01-29 05:15 UTC, auscompgeek approved these changes
LGTM with comments

2023-01-29 05:15 UTC, auscompgeek commented on components/gripper.py
> +            self.solenoid.set(value=DoubleSolenoid.Value.kReverse)
nit: it's already obvious we're setting the value
```suggestion
            self.solenoid.set(DoubleSolenoid.Value.kForward)
        else:
            self.solenoid.set(DoubleSolenoid.Value.kReverse)
```

2023-01-29 05:15 UTC, auscompgeek commented on ids.py
> +class DioChannels:
I think this needs to be added to the test

2023-01-29 05:15 UTC, auscompgeek commented on components/gripper.py
> +    def __init__(self):
Ensure all the methods are covered by the type checker.

```suggestion
    def __init__(self) -> None:
```

2023-02-01 06:37 UTC, merged