Pathfinding
thedropbears/pychargedup pull request #67
Opened 2023-02-17 07:19 UTC by OliverW10

Adds pathfinding utility and swaps movement trajectory generation to useing pathplanner rather than the wpilib trajectories

2023-02-17 08:55 UTC, auscompgeek commented on utilities/pathfinding.py
> +    def __eq__(self, __o: object) -> bool:
Why are we defining our own `__eq__` instead of the generated one?

2023-02-20 07:56 UTC, auscompgeek requested changes
See inline comments

2023-02-20 07:56 UTC, auscompgeek commented on requirements.txt
> +robotpy[apriltag,cscore,pathplannerlib]~=2023.3.2
I thought we wanted to only use the `robotpy` package to pin WPILib packages?

2023-02-20 07:56 UTC, auscompgeek commented on requirements.txt
> +astar
Please keep this in alphabetical order.

2023-02-20 07:56 UTC, auscompgeek commented on requirements.txt
>  numpy~=1.24.1
Pipfile needs to be updated at the same time.

2023-03-04 23:22 UTC, closed without merging

2023-03-04 23:22 UTC, LucienMorey commented
Probs not going to use it ay